### ISSUE TITLE
No favicon

### ISSUE THREAD

**Issue by michaelachrisco** [westernmilling/chancellor#50]
Trying out the app and I found something small:

16:20:33 web.1  | ActionController::RoutingError (No route matches [GET] "/images/favicon.ico"):
16:20:33 web.1  |   actionpack (4.1.8) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
16:20:33 web.1  |   actionpack (4.1.8) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
16:20:33 web.1  |   railties (4.1.8) lib/rails/rack/logger.rb:38:in `call_app'
16:20:33 web.1  |   railties (4.1.8) lib/rails/rack/logger.rb:22:in `call'
16:20:33 web.1  |   request_store (1.1.0) lib/request_store/middleware.rb:8:in `call'
16:20:33 web.1  |   actionpack (4.1.8) lib/action_dispatch/middleware/request_id.rb:21:in `call'
16:20:33 web.1  |   rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
16:20:33 web.1  |   rack (1.5.2) lib/rack/runtime.rb:17:in `call'
16:20:33 web.1  |   activesupport (4.1.8) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
16:20:33 web.1  |   rack (1.5.2) lib/rack/lock.rb:17:in `call'
16:20:33 web.1  |   actionpack (4.1.8) lib/action_dispatch/middleware/static.rb:84:in `call'
16:20:33 web.1  |   rack (1.5.2) lib/rack/sendfile.rb:112:in `call'
16:20:33 web.1  |   airbrake (4.1.0) lib/airbrake/user_informer.rb:16:in `_call'
16:20:33 web.1  |   airbrake (4.1.0) lib/airbrake/user_informer.rb:12:in `call'
16:20:33 web.1  |   railties (4.1.8) lib/rails/engine.rb:514:in `call'
16:20:33 web.1  |   railties (4.1.8) lib/rails/application.rb:144:in `call'
16:20:33 web.1  |   puma (2.11.0) lib/puma/rack_patch.rb:13:in `call'
16:20:33 web.1  |   puma (2.11.0) lib/puma/configuration.rb:82:in `call'
16:20:33 web.1  |   puma (2.11.0) lib/puma/server.rb:507:in `handle_request'
16:20:33 web.1  |   puma (2.11.0) lib/puma/server.rb:375:in `process_client'
16:20:33 web.1  |   puma (2.11.0) lib/puma/server.rb:262:in `block in run'
16:20:33 web.1  |   puma (2.11.0) lib/puma/thread_pool.rb:104:in `call'
16:20:33 web.1  |   puma (2.11.0) lib/puma/thread_pool.rb:104:in `block in spawn_thread'

**Comment by josephbridgwaterrowe** [comment]
@michaelachrisco thanks for this branch.

However, I would like to come up with a chancellor specific icon and not the WM wheat icon.

Once I've created an icon I will update this branch and PR.

Thanks.
